"""Embed the dependency-free web console in firmware Flash before compilation."""

Import("env")

import gzip
from pathlib import Path


source_dir = Path(env.subst("$PROJECT_SRC_DIR")).resolve()
project_dir = source_dir.parent.parent
web_dir = project_dir / "web"
generated_dir = project_dir / "firmware" / "generated"
generated_dir.mkdir(parents=True, exist_ok=True)

mime_types = {
    ".html": "text/html; charset=utf-8",
    ".css": "text/css; charset=utf-8",
    ".js": "text/javascript; charset=utf-8",
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".ico": "image/x-icon",
}

assets = []
for file in sorted(web_dir.rglob("*")):
    if not file.is_file():
        continue
    route = "/" + file.relative_to(web_dir).as_posix()
    mime = mime_types.get(file.suffix.lower(), "application/octet-stream")
    assets.append((route, mime, gzip.compress(file.read_bytes(), compresslevel=9, mtime=0)))

if not any(route == "/index.html" for route, _, _ in assets):
    raise RuntimeError("web/index.html is required for the onboard console")

lines = [
    "// Generated by scripts/embed_web_assets.py. Do not edit.",
    "#pragma once",
    "#include <Arduino.h>",
    "struct EmbeddedWebAsset {",
    "  const char* path;",
    "  const char* contentType;",
    "  const uint8_t* data;",
    "  size_t size;",
    "};",
]
for index, (_, _, data) in enumerate(assets):
    lines.append(f"inline const uint8_t kEmbeddedWebAsset{index}[] PROGMEM = {{")
    for offset in range(0, len(data), 16):
        lines.append("  " + ", ".join(f"0x{byte:02x}" for byte in data[offset:offset + 16]) + ",")
    lines.append("};")

lines.append("inline const EmbeddedWebAsset kEmbeddedWebAssets[] = {")
for index, (route, mime, _) in enumerate(assets):
    lines.append(
        f'  {{"{route}", "{mime}", kEmbeddedWebAsset{index}, sizeof(kEmbeddedWebAsset{index})}},'
    )
lines.extend([
    "};",
    "inline constexpr size_t kEmbeddedWebAssetCount = sizeof(kEmbeddedWebAssets) / sizeof(kEmbeddedWebAssets[0]);",
    "",
])

header = generated_dir / "EmbeddedWebAssets.h"
contents = "\n".join(lines)
if not header.exists() or header.read_text(encoding="utf-8") != contents:
    header.write_text(contents, encoding="utf-8")

env.Append(CPPPATH=[str(generated_dir)])
print(f"Embedded {len(assets)} web assets ({sum(len(data) for _, _, data in assets)} gzip bytes)")
